apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phapp
  name: phapp
  namespace: ph-jsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phapp
  strategy: {}
  template:
    metadata:
      labels:
        app: phapp
    spec:
      containers:
      - image: phacerqueira/nginx_jsapp:1.3
        name: ph-jsapp-4mz7n
        ports:
        - containerPort: 80
        resources: 
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "50m"
status: {}
