apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phapp
  name: phapp
  namespace: ph-jsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phapp
  strategy: {}
  template:
    metadata:
      labels:
        app: phapp
    spec:
      containers:
      - image: phacerqueira/nginx_jsapp:1.3
        name: ph-jsapp
        ports:
        - containerPort: 80
          name: http-web-svc
        resources: 
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
status: {}
