apiVersion: v1
kind: Service
metadata:
  name: jsapp-service
  namespace: ph-jsapp
spec:
  selector:
    app: phapp
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc